spring.application.name=proyectomdweb

#-- RUTA / CONTEXT PATH DEL PROYECTO --#
server.port=8080
server.address=0.0.0.0

# Deshabilitar docker compose automático ya que usamos base de datos local
spring.docker.compose.enabled=false

#-- CONFIGURACIÓN DE BD POSTGRESQL (Puerto 5432) --#
spring.datasource.url=jdbc:postgresql://localhost:5432/LLAMABD?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=antonela
spring.datasource.driver-class-name=org.postgresql.Driver

#-- CONFIGURACIÓN JPA/HIBERNATE --#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#-- CONFIGURACIÓN DE CORREO ELECTRÓNICO (SMTP GMAIL / OUTLOOK) --#
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:soporte.lamodatellama@gmail.com}
spring.mail.password=${MAIL_PASSWORD:clave_de_aplicacion}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
