spring.application.name=proyectomdweb
server.port=8080

# Configuracion para respuestas de error detalladas en desarrollo
server.error.include-message=always
server.error.include-binding-errors=always
