spring.application.name=productos-api
server.port=8080

# Muestra detalles basicos de error durante el laboratorio.
# En produccion no se recomienda exponer mensajes internos.
server.error.include-message=always
