spring.application.name=tienda

# ===============================
# MYSQL
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3307/tienda_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT
# ===============================

app.jwt.issuer=http://localhost:8080
app.jwt.ttl-minutes=30
app.jwt.secret-base64=${JWT_SECRET_BASE64}

# ===============================
# SERVER
# ===============================

server.port=8090