spring.application.name=semana4-api-rest
server.port=8080

# Muestra detalles basicos de error durante el laboratorio.
# En produccion no se recomienda exponer mensajes internos.
server.error.include-message=always
server.error.include-binding-errors=always
