# Perfil MySQL para el Laboratorio 7
# Ejecutar con: ./mvnw spring-boot:run -Dspring-boot.run.profiles=mysql
# Antes crear la BD:  CREATE DATABASE dwi_lmll;
spring.datasource.url=jdbc:mysql://localhost:3306/dwi_lmll?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.h2.console.enabled=false
