spring.application.name=dwi_lmll
server.port=8090
spring.datasource.url=jdbc:h2:mem:dwi_lmll
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create

spring.h2.console.enabled=true
# Datos iniciales (data.sql) se cargan despues de que Hibernate cree las tablas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
