spring.application.name=tienda

spring.datasource.url=jdbc:mysql://localhost:3306/tienda_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=TU_CLAVE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# --- JWT (Laboratorio 9) ---
# Clave de solo lectura para el laboratorio. En produccion usar variable de entorno.
app.jwt.secret-base64=dXRwLWxhYjktdGllbmRhLWp3dC1oczI1Ni1jbGF2ZS0yMDI2IQ==
app.jwt.issuer=https://tienda-api.utm.edu.pe
app.jwt.ttl-minutes=30
